### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by NosferatuUK** [zDestinate/INS_Sandstorm_DiscordChat#2]
Would it be possible for a better instructional video or readme? as visual explains a thousand words.

I have tried setting up the bot to use the advanced chat in my insurgency server... let me explain so far what i have done.

*Server has the advanced chat running (colours works and bold etc) the mutator is in the start up line of the server.bat AND the log command from the bot installation guide is in the start up line too.

*I have gone to discord and created a bot and gave some permissions from the discord faq tutorial and added it to the permanent discord server. 

*I have downloaded and installed the nodejs and I have placed the the script files in a folder called BOT in the  directory: C:\Server#01\BOT\

*I have then done npm install in command whilst CD to that directory and it installs:

```
C:\Server#01\BOT>npm install
npm WARN discord.js@11.6.4 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN discordchat@1.0.0 No repository field.

audited 14 packages in 0.649s
found 0 vulnerabilities
```

```
C:\Server#01\BOT>npm start

> discordchat@1.0.0 start C:\Server#01\BOT
> node server/main.js

internal/modules/cjs/loader.js:1109
    throw err;
    ^

SyntaxError: C:\Server#01\BOT\configs.json: Unexpected token S in JSON at position 234
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Server#01\BOT\server\main.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discordchat@1.0.0 start: `node server/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discordchat@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Server\AppData\Roaming\npm-cache\_logs\2021-01-01T21_17_54_894Z-debug.log
```

So far the bot stays offline in the required chat channel (all channels in fact).
The advanced chat works in the Insurgency server.
I have added the connection settings in the config.json before installing the npm package.

the config.json file is:

```
{
	"RconIP": "2.######.40",
	"RconPort": 27017,
	"RconPassword": "#######",
	"discord":
	{
		"botToken": "Nzk0NjY#####NDE0.X--GPg.cVFM-Xc#######xCnuPDHlI",
		"ChatChannel": "server01"
	},
	"LogFilePath": "C:\Server#01\steamapps\common\sandstorm_server\Insurgency\Saved\Logs\Insurgency.log"
}
```

Any help would be great :)

**Comment by NosferatuUK** [comment]
Turns out that even though i have it installed in:
C:\Server#01\BOT

The log file path in config.js cannot read \ locations, only /

So the WRONG path i was using:
LogFilePath": "C:\Server#01\steamapps\common\sandstorm_server\Insurgency\Saved\Logs\Insurgency.log"

Should be: 

LogFilePath": "../steamapps/common/sandstorm_server/Insurgency/Saved/Logs/Insurgency.log"

The "../” at the start allows the running script to jump back out of my folder from "C:\Server#01\BOT\server" to "C:\Server#01\" so it can now continue to search to the correct log file path.

Also the default path is: "sandstorm/Insurgency/Saved/Logs/Insurgency.log"

But if your using the dedicated steamcmd.exe installer for insurgency, then the path is: sandstorm_server/Insurgency/

**Comment by zDestinate** [comment]
Sorry for the late reply. The path can only understand the / instead of \\
I put the pathing example in the configs. It was tested on a Linux server. Not sure if you can put a C:/ path in there for windows.
Have you tried "C:/Server#01/steamapps/common/sandstorm_server/Insurgency/Saved/Logs/Insurgency.log"?
